### ISSUE TITLE
SET issues in Scripts member object in package JSON files 

### ISSUE THREAD

**Issue by DominicSimpson** [fac26/week3-auth-linnk#60]
There are a number of modules in the scripts member object in package.json which utilize SET and ampersands so that these modules can be ran in PowerShell. The problem with doing this is that it then makes it difficult to run these files in WSL (and probably Bash Terminal). 
The default should be to not include this modification in package.json, and to always use WSL in the Terminal when running anything in Node.

![screenshot3](https://user-images.githubusercontent.com/52511353/216117555-6c3ef154-ec15-486d-8bae-16dcf4312138.png)

**Comment by Psydwinder** [comment]
Heya @DominicSimpson,

I had a discussion with Neville about this. As WSL refuses to run on my computer and in the real world we cannot assume everyone has WSL installed, we can have a separate script for windows to run. 

But as it stands "dev" is for anyone running Mac and WSL on Windows. "dev-win" is for anyone with WSL on windows.
